import type { CSSProperties } from 'react'
import {
  getMainSettingsTabButtonStyle,
  mainSettingsPageTitleStyle,
  mainSettingsTabBarStyle,
  mainSettingsTabRowStyle,
  MAIN_SETTINGS_FONT_SIZE,
  MAIN_SETTINGS_RADIUS,
} from './mainSettingsTokens'

export const generalSettingsStyles: Record<string, CSSProperties> = {
  wrapper: {
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#141414',
    padding: 'clamp(16px, 3vw, 20px) clamp(12px, 4vw, 24px)',
  },
  pageTitle: {
    ...mainSettingsPageTitleStyle,
  },
  tabsBar: {
    ...mainSettingsTabBarStyle,
  },
  tabsWrapper: {
    ...mainSettingsTabRowStyle,
  },
  notice: {
    fontSize: MAIN_SETTINGS_FONT_SIZE.base,
    color: '#555',
    fontWeight: 300,
    marginBottom: '20px',
  },
  divider: {
    border: 'none',
    borderTop: '1px solid #d0d0d0',
    margin: '20px 0',
  },
  sectionTitle: {
    fontSize: MAIN_SETTINGS_FONT_SIZE.lg,
    fontWeight: 600,
    color: '#141414',
    marginBottom: '4px',
  },
  sectionSubtitle: {
    fontSize: MAIN_SETTINGS_FONT_SIZE.sm,
    fontWeight: 300,
    color: '#555',
    marginBottom: '16px',
  },
  fieldGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: MAIN_SETTINGS_FONT_SIZE.base,
    fontWeight: 600,
    color: '#141414',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    maxWidth: '500px',
    padding: '8px 12px',
    fontSize: MAIN_SETTINGS_FONT_SIZE.input,
    height: '40px',
    fontWeight: 300,
    color: '#141414',
    border: '1px solid #b8b8b8',
    borderRadius: MAIN_SETTINGS_RADIUS.md,
    background: '#fff',
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    outline: 'none',
    display: 'block',
  } as CSSProperties,
  select: {
    width: '100%',
    maxWidth: '500px',
    padding: '8px 36px 8px 12px',
    fontSize: MAIN_SETTINGS_FONT_SIZE.input,
    fontWeight: 300,
    height: '40px',
    color: '#141414',
    border: '1px solid #b8b8b8',
    borderRadius: MAIN_SETTINGS_RADIUS.md,
    background: '#fff',
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    outline: 'none',
    display: 'block',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath d='M6 8L1 3h10z' fill='%23555'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 12px center',
  } as CSSProperties,
  helpText: {
    fontSize: MAIN_SETTINGS_FONT_SIZE.sm,
    color: '#555',
    fontWeight: 300,
    marginTop: '6px',
    lineHeight: '1.5',
  },
  link: {
    color: '#006162',
    textDecoration: 'none',
  } as CSSProperties,
  saveButton: {
    marginTop: '32px',
    padding: '9px 22px',
    fontSize: MAIN_SETTINGS_FONT_SIZE.base,
    fontWeight: 400,
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#fff',
    background: '#006162',
    border: 'none',
    borderRadius: MAIN_SETTINGS_RADIUS.md,
    cursor: 'pointer',
  } as CSSProperties,
  profileImageBox: {
    width: '72px',
    height: '72px',
    borderRadius: MAIN_SETTINGS_RADIUS.full,
    background: 'linear-gradient(135deg, #0d6efd 0%, #198754 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: MAIN_SETTINGS_FONT_SIZE.display,
    fontWeight: 700,
    color: '#fff',
    cursor: 'pointer',
    overflow: 'hidden',
    border: '2px solid #e0e0e0',
  } as CSSProperties,
  changePhotoBtn: {
    marginTop: '10px',
    padding: '6px 14px',
    fontSize: MAIN_SETTINGS_FONT_SIZE.sm,
    fontWeight: 300,
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#141414',
    background: 'transparent',
    border: '1px solid #c4c4c4',
    borderRadius: MAIN_SETTINGS_RADIUS.md,
    cursor: 'pointer',
    display: 'block',
  } as CSSProperties,
  helpIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '16px',
    height: '16px',
    border: '1.5px solid #888',
    borderRadius: MAIN_SETTINGS_RADIUS.full,
    fontSize: MAIN_SETTINGS_FONT_SIZE.xs,
    color: '#888',
    verticalAlign: 'middle',
    marginLeft: '4px',
    cursor: 'default',
  } as CSSProperties,
  checkboxRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    marginBottom: '16px',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    marginTop: '2px',
    accentColor: '#000000',
    cursor: 'pointer',
    flexShrink: 0,
  } as CSSProperties,
  checkboxLabel: {
    fontSize: MAIN_SETTINGS_FONT_SIZE.base,
    fontWeight: '500',
    color: '#141414',
    lineHeight: '1.5',
    cursor: 'pointer',
  },
}

export function getGeneralSettingsTabStyle(
  isActive: boolean,
  isFirst: boolean,
  isLast: boolean,
): CSSProperties {
  return getMainSettingsTabButtonStyle({
    isActive,
    isFirst,
    isLast,
    fontFamily: 'Lexend Deca, Helvetica, Arial, sans-serif',
  })
}
