import type { CSSProperties } from 'react'

export const generalSettingsStyles: Record<string, CSSProperties> = {
  wrapper: {
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#141414',
    padding: '32px 40px',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#141414',
    marginBottom: '24px',
    letterSpacing: 0,
  },
  tabsWrapper: {
    display: 'flex',
    marginBottom: '32px',
    overflow: 'hidden',
  },
  notice: {
    fontSize: '14px',
    color: '#555',
    fontWeight: 300,
    marginBottom: '28px',
  },
  divider: {
    border: 'none',
    borderTop: '1px solid #e8e8e8',
    margin: '28px 0',
  },
  sectionTitle: {
    fontSize: '20px',
    fontWeight: 600,
    color: '#141414',
    marginBottom: '4px',
  },
  sectionSubtitle: {
    fontSize: '13px',
    fontWeight: 300,
    color: '#555',
    marginBottom: '24px',
  },
  fieldGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 600,
    color: '#141414',
    marginBottom: '8px',
  },
  input: {
    width: '500px',
    padding: '8px 12px',
    fontSize: '16px',
    height: '40px',
    fontWeight: 300,
    color: '#141414',
    border: '1px solid #d0d0d0',
    borderRadius: '4px',
    background: '#fff',
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    outline: 'none',
    display: 'block',
  } as CSSProperties,
  select: {
    width: '500px',
    padding: '8px 36px 8px 12px',
    fontSize: '16px',
    fontWeight: 300,
    height: '40px',
    color: '#141414',
    border: '1px solid #d0d0d0',
    borderRadius: '4px',
    background: '#fff',
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    outline: 'none',
    display: 'block',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath d='M6 8L1 3h10z' fill='%23555'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 12px center',
  } as CSSProperties,
  helpText: {
    fontSize: '13px',
    color: '#555',
    fontWeight: 300,
    marginTop: '6px',
    lineHeight: '1.5',
  },
  link: {
    color: '#006162',
    textDecoration: 'none',
  } as CSSProperties,
  saveButton: {
    marginTop: '32px',
    padding: '9px 22px',
    fontSize: '14px',
    fontWeight: 400,
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#fff',
    background: '#006162',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  } as CSSProperties,
  profileImageBox: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #0d6efd 0%, #198754 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    fontWeight: 700,
    color: '#fff',
    cursor: 'pointer',
    overflow: 'hidden',
    border: '2px solid #e0e0e0',
  } as CSSProperties,
  changePhotoBtn: {
    marginTop: '10px',
    padding: '6px 14px',
    fontSize: '13px',
    fontWeight: 300,
    fontFamily: "'Lexend Deca', Helvetica, Arial, sans-serif",
    color: '#141414',
    background: 'transparent',
    border: '1px solid #e0e0e0',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'block',
  } as CSSProperties,
  helpIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '16px',
    height: '16px',
    border: '1.5px solid #888',
    borderRadius: '50%',
    fontSize: '10px',
    color: '#888',
    verticalAlign: 'middle',
    marginLeft: '4px',
    cursor: 'default',
  } as CSSProperties,
  checkboxRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    marginBottom: '16px',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    marginTop: '2px',
    accentColor: '#000000',
    cursor: 'pointer',
    flexShrink: 0,
  } as CSSProperties,
  checkboxLabel: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#141414',
    lineHeight: '1.5',
    cursor: 'pointer',
  },
}

export function getGeneralSettingsTabStyle(isActive: boolean, isLast: boolean): CSSProperties {
  return {
    padding: '12px 28px',
    background: isActive ? '#ffffff' : 'whitesmoke',
    border: '1px solid #e0e0e0',
    borderRight: isLast ? '1px solid #e0e0e0' : 'none',
    borderBottom: isActive ? '2px solid #ffffff' : '2px solid #e0e0e0',
    cursor: 'pointer',
    fontFamily: 'Lexend Deca, Helvetica, Arial, sans-serif',
    fontSize: '14px',
    fontWeight: 300,
    color: '#141414',
    whiteSpace: 'nowrap',
    transition: 'background 0.15s',
    position: 'relative',
    top: '1px',
    outline: 'none',
  }
}
