sonar.projectKey=PRIME-ALLEY-TECHNOLOGY-LLC_main-app-microservice
sonar.organization=prime-alley-technology-llc
# Only analyze source code inside src
sonar.sources=src

# Optional but recommended for JS/TS
sonar.exclusions=**/node_modules/**,**/*.json

# Tests live under src/__tests__ (JS + TS)
sonar.tests=src/__tests__
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.spec.js,src/**/*.test.js,src/pages/billing/customer/order-invoicing/index.tsx

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=main-app-microservice
#sonar.projectVersion=1.0

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S7924
sonar.issue.ignore.multicriteria.e1.resourceKey=**

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8