sonar.projectKey=PRIME-ALLEY-TECHNOLOGY-LLC_main-app-microservice
sonar.organization=prime-alley-technology-llc
# Only analyze source code inside src
sonar.sources=src

# Optional but recommended for JS/TS
sonar.exclusions=**/node_modules/**,**/*.json

# If you want tests excluded from LOC
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=main-app-microservice
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8