import type { CSSProperties } from "react";

export const transactionPageFont = "Lexend Deca, Helvetica, Arial, sans-serif";

export const transactionPageStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily: transactionPageFont,
    color: "#141414",
    backgroundColor: "#f5f5f5",
    minHeight: "100vh",
    padding: "24px",
  },
  pageHeading: {
    fontSize: 24,
    fontWeight: 300,
    fontFamily: transactionPageFont,
    color: "#141414",
    margin: "0 0 20px 0",
    lineHeight: "29px",
  },
  tableWrapper: {
    backgroundColor: "#fff",
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 8,
    boxShadow: "rgba(20, 20, 20, 0.08) 0px 1px 8px 0px",
    overflow: "hidden",
    width: "100%",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontFamily: transactionPageFont,
  },
  thead: {
    backgroundColor: "#f5f5f5",
    borderBottom: "1px solid #e5e5e5",
  },
  th: {
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: transactionPageFont,
    color: "#141414",
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
    letterSpacing: 0,
    lineHeight: "18px",
  },
  td: {
    padding: "16px 16px",
    fontSize: 14,
    fontFamily: transactionPageFont,
    color: "#141414",
    verticalAlign: "top" as const,
    borderBottom: "1px solid #e5e5e5",
    lineHeight: "20px",
  },
  dateCell: {
    fontSize: 14,
    fontFamily: transactionPageFont,
    color: "#141414",
    fontWeight: 400,
    whiteSpace: "nowrap" as const,
  },
  detailsTitle: {
    fontSize: 14,
    fontWeight: 500,
    fontFamily: transactionPageFont,
    color: "#141414",
    marginBottom: 2,
  },
  detailsSub: {
    fontSize: 12,
    fontWeight: 300,
    fontFamily: transactionPageFont,
    color: "#666",
    marginBottom: 8,
  },
  actionLinks: {
    display: "flex",
    alignItems: "center",
    gap: 0,
  },
  link: {
    fontWeight: 600,
    color: "rgb(0, 97, 98)",
    cursor: "pointer",
    textUnderlineOffset: "24%",
    textDecoration: "underline",
    fontFamily: transactionPageFont,
    fontSize: 14,
  },
  divider: {
    color: "#ccc",
    margin: "0 8px",
    fontWeight: 300,
    fontSize: 14,
  },
  amountLabel: {
    fontSize: 12,
    fontWeight: 300,
    fontFamily: transactionPageFont,
    color: "#666",
    marginBottom: 2,
  },
  amountValue: {
    fontSize: 14,
    fontWeight: 400,
    fontFamily: transactionPageFont,
    color: "#141414",
    marginBottom: 12,
  },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #141414",
    borderRadius: 20,
    padding: "4px 14px",
    fontSize: 13,
    fontWeight: 400,
    fontFamily: transactionPageFont,
    color: "#141414",
    whiteSpace: "nowrap" as const,
    backgroundColor: "#fff",
  },
  statusBadgeSuccess: {
    border: "1px solid #16a34a",
    color: "#166534",
    backgroundColor: "#dcfce7",
  },
  statusBadgeDanger: {
    border: "1px solid #ef4444",
    color: "#991b1b",
    backgroundColor: "#fee2e2",
  },
};
