import type { CSSProperties } from "react";

export const paymentMethodsFont = "Lexend Deca, Helvetica, Arial, sans-serif";

export const paymentMethodsStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily: paymentMethodsFont,
    color: "#141414",
    backgroundColor: "#f5f5f5",
    minHeight: "100vh",
    padding: "24px",
    position: "relative" as const,
  },
  topRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  pageHeading: {
    fontSize: 24,
    fontWeight: 300,
    fontFamily: paymentMethodsFont,
    color: "#141414",
    margin: 0,
    lineHeight: "29px",
  },
  btnDark: {
    backgroundColor: "rgb(20, 20, 20)",
    borderColor: "rgba(20, 20, 20, 0)",
    color: "rgb(255, 255, 255)",
    textDecoration: "none",
    borderRadius: 4,
    borderWidth: 1,
    borderStyle: "solid",
    verticalAlign: "middle",
    paddingBlock: 10,
    paddingInline: 24,
    fontFamily: paymentMethodsFont,
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: "18px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  btnLight: {
    backgroundColor: "#fff",
    borderColor: "rgb(204,204,204)",
    color: "rgb(20,20,20)",
    textDecoration: "none",
    borderRadius: 4,
    borderWidth: 1,
    borderStyle: "solid",
    verticalAlign: "middle",
    paddingBlock: 10,
    paddingInline: 24,
    fontFamily: paymentMethodsFont,
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: "18px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
  },
  tableWrapper: {
    backgroundColor: "#fff",
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 8,
    boxShadow: "rgba(20, 20, 20, 0.08) 0px 1px 8px 0px",
    overflow: "visible",
    width: "100%",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontFamily: paymentMethodsFont,
  },
  thead: {
    backgroundColor: "#f5f5f5",
    borderBottom: "1px solid #e5e5e5",
  },
  th: {
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: paymentMethodsFont,
    color: "#141414",
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
    letterSpacing: 0,
    lineHeight: "18px",
  },
  td: {
    padding: "20px 16px",
    fontSize: 14,
    fontFamily: paymentMethodsFont,
    color: "#141414",
    verticalAlign: "middle" as const,
    lineHeight: "22px",
  },
  visaChip: {
    background: "#1a1f71",
    color: "#fff",
    fontSize: 9,
    fontWeight: 700,
    padding: "3px 7px",
    borderRadius: 3,
    letterSpacing: 0.5,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    flexShrink: 0,
  },
  addressLink: {
    color: "rgb(0,97,98)",
    fontWeight: 400,
    fontSize: 14,
    fontFamily: paymentMethodsFont,
    textDecoration: "none",
    display: "block",
    lineHeight: "22px",
  },
  productLink: {
    color: "rgb(0,97,98)",
    fontWeight: 600,
    fontSize: 14,
    fontFamily: paymentMethodsFont,
    textDecoration: "underline",
    textUnderlineOffset: "24%",
    cursor: "pointer",
  },
  actionsBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    fontFamily: paymentMethodsFont,
    fontSize: 14,
    fontWeight: 700,
    color: "#141414",
    cursor: "pointer",
    padding: 0,
  },
  overlay: {
    position: "fixed" as const,
    inset: 0,
    backgroundColor: "rgba(20,20,20,0.35)",
    zIndex: 100,
  },
  sidebar: {
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 0,
    boxShadow: "rgba(20, 20, 20, 0.08) 0px 16px 32px 0px",
    position: "fixed" as const,
    top: 0,
    bottom: 0,
    right: 0,
    minWidth: 300,
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column" as const,
    width: 700,
    backgroundColor: "rgb(255, 255, 255)",
    zIndex: 99999,
    overflowY: "auto" as const,
  },
  sidebarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px",
    borderBottom: "1px solid #e5e5e5",
    flexShrink: 0,
  },
  sidebarTitle: {
    color: "rgb(20,20,20)",
    fontSize: 20,
    fontWeight: 600,
    lineHeight: "24px",
    fontFamily: paymentMethodsFont,
    margin: 0,
  },
  closeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#666",
    display: "flex",
    alignItems: "center",
    padding: 4,
  },
  sidebarBody: {
    flex: 1,
    padding: "24px",
    overflowY: "auto" as const,
  },
  sidebarFooter: {
    padding: "16px 24px",
    borderTop: "1px solid #e5e5e5",
    display: "flex",
    gap: 12,
    flexShrink: 0,
    backgroundColor: "#fff",
  },
  fieldLabel: {
    fontSize: 14,
    fontStyle: "unset",
    fontWeight: 600,
    textTransform: "unset" as const,
    color: "rgb(20,20,20)",
    fontFamily: paymentMethodsFont,
    letterSpacing: 0,
    lineHeight: "18px",
    display: "block",
    marginBottom: 6,
    marginTop: 16,
  },
  input: {
    backgroundColor: "rgb(255,255,255)",
    border: "1px solid rgb(138,138,138)",
    borderRadius: 4,
    color: "rgb(20,20,20)",
    display: "block",
    fontFamily: paymentMethodsFont,
    fontSize: 16,
    fontWeight: 400,
    height: 40,
    lineHeight: "24px",
    letterSpacing: 0,
    paddingInline: 16,
    paddingBlock: 8,
    width: "100%",
    boxSizing: "border-box" as const,
    outline: "none",
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    cursor: "pointer",
  },
  checkbox: {
    width: 18,
    height: 18,
    border: "2px solid #141414",
    borderRadius: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#141414",
    flexShrink: 0,
    cursor: "pointer",
  },
  checkLabel: {
    fontSize: 14,
    fontFamily: paymentMethodsFont,
    color: "#141414",
    cursor: "pointer",
  },
  sectionDivider: {
    border: "none",
    borderTop: "1px solid #e5e5e5",
    margin: "24px 0",
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: 700,
    fontFamily: paymentMethodsFont,
    color: "#141414",
    margin: "0 0 12px 0",
  },
  infoText: {
    fontSize: 13,
    fontFamily: paymentMethodsFont,
    color: "rgb(0,97,98)",
    margin: "0 0 12px 0",
    lineHeight: "20px",
  },
  addressText: {
    fontSize: 14,
    fontFamily: paymentMethodsFont,
    color: "rgb(0,97,98)",
    lineHeight: "22px",
    margin: 0,
  },
  subscriptionBox: {
    border: "1px solid #ccc",
    borderRadius: 4,
    padding: "12px 16px",
    backgroundColor: "#f5f5f5",
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
  },
};
