export interface Language {
  value: string;
  label: string;
}

export const languages: Language[] = [
  { value: 'english', label: 'English' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'french', label: 'French' },
  { value: 'german', label: 'German' },
  { value: 'italian', label: 'Italian' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'russian', label: 'Russian' },
  { value: 'chinese-mandarin', label: 'Chinese (Mandarin)' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'korean', label: 'Korean' },
  { value: 'arabic', label: 'Arabic' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'dutch', label: 'Dutch' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'polish', label: 'Polish' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'vietnamese', label: 'Vietnamese' },
  { value: 'thai', label: 'Thai' },
  { value: 'indonesian', label: 'Indonesian' },
  { value: 'malay', label: 'Malay' },
  { value: 'hebrew', label: 'Hebrew' },
  { value: 'persian-farsi', label: 'Persian (Farsi)' },
  { value: 'urdu', label: 'Urdu' },
  { value: 'bengali', label: 'Bengali' },
  { value: 'tamil', label: 'Tamil' },
  { value: 'telugu', label: 'Telugu' },
  { value: 'marathi', label: 'Marathi' },
  { value: 'gujarati', label: 'Gujarati' },
  { value: 'kannada', label: 'Kannada' },
  { value: 'malayalam', label: 'Malayalam' },
  { value: 'punjabi', label: 'Punjabi' },
  { value: 'czech', label: 'Czech' },
  { value: 'hungarian', label: 'Hungarian' },
  { value: 'romanian', label: 'Romanian' },
  { value: 'greek', label: 'Greek' },
  { value: 'finnish', label: 'Finnish' },
  { value: 'danish', label: 'Danish' },
  { value: 'norwegian', label: 'Norwegian' },
  { value: 'ukrainian', label: 'Ukrainian' },
  { value: 'bulgarian', label: 'Bulgarian' },
  { value: 'croatian', label: 'Croatian' },
  { value: 'serbian', label: 'Serbian' },
  { value: 'slovak', label: 'Slovak' },
  { value: 'slovenian', label: 'Slovenian' },
  { value: 'estonian', label: 'Estonian' },
  { value: 'latvian', label: 'Latvian' },
  { value: 'lithuanian', label: 'Lithuanian' },
  { value: 'macedonian', label: 'Macedonian' },
  { value: 'albanian', label: 'Albanian' },
  { value: 'swahili', label: 'Swahili' },
  { value: 'afrikaans', label: 'Afrikaans' },
  { value: 'zulu', label: 'Zulu' },
  { value: 'xhosa', label: 'Xhosa' },
  { value: 'amharic', label: 'Amharic' },
  { value: 'yoruba', label: 'Yoruba' },
  { value: 'igbo', label: 'Igbo' },
  { value: 'hausa', label: 'Hausa' },
  { value: 'nepali', label: 'Nepali' },
  { value: 'sinhala', label: 'Sinhala' },
  { value: 'myanmar-burmese', label: 'Myanmar (Burmese)' },
  { value: 'khmer', label: 'Khmer' },
  { value: 'lao', label: 'Lao' },
  { value: 'georgian', label: 'Georgian' },
  { value: 'armenian', label: 'Armenian' },
  { value: 'azerbaijani', label: 'Azerbaijani' },
  { value: 'kazakh', label: 'Kazakh' },
  { value: 'kyrgyz', label: 'Kyrgyz' },
  { value: 'uzbek', label: 'Uzbek' },
  { value: 'mongolian', label: 'Mongolian' },
  { value: 'chinese-traditional', label: 'Chinese (Traditional)' },
  { value: 'chinese-simplified', label: 'Chinese (Simplified)' },
  { value: 'catalan', label: 'Catalan' },
  { value: 'basque', label: 'Basque' },
  { value: 'galician', label: 'Galician' },
  { value: 'welsh', label: 'Welsh' },
  { value: 'irish', label: 'Irish' },
  { value: 'maltese', label: 'Maltese' },
  { value: 'icelandic', label: 'Icelandic' },
  { value: 'belarusian', label: 'Belarusian' },
  { value: 'bosnian', label: 'Bosnian' }
];

