import type { CSSProperties } from "react";
import { documentPageFont } from "./documentPageHelpers";

export const documentPageStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily: documentPageFont,
    color: "#141414",
    backgroundColor: "#f5f5f5",
    minHeight: "100vh",
    padding: "24px",
  },
  pageHeading: {
    fontSize: 24,
    fontWeight: 300,
    fontFamily: documentPageFont,
    color: "#141414",
    margin: "0 0 20px 0",
    lineHeight: "29px",
  },
  pageHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap" as const,
    gap: 12,
    marginBottom: 20,
  },
  primaryButton: {
    fontFamily: documentPageFont,
    fontSize: 14,
    fontWeight: 600,
    color: "#fff",
    backgroundColor: "rgb(0, 97, 98)",
    border: "none",
    borderRadius: 8,
    padding: "10px 20px",
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  modalHint: {
    fontFamily: documentPageFont,
    fontSize: 13,
    color: "#666",
    marginBottom: 12,
  },
  fileList: {
    marginTop: 16,
    paddingLeft: 20,
    fontFamily: documentPageFont,
    fontSize: 14,
    color: "#141414",
  },
  tableWrapper: {
    backgroundColor: "#fff",
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 8,
    boxShadow: "rgba(20, 20, 20, 0.08) 0px 1px 8px 0px",
    overflow: "hidden",
    width: "100%",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontFamily: documentPageFont,
  },
  thead: {
    backgroundColor: "#f5f5f5",
    borderBottom: "1px solid #e5e5e5",
  },
  th: {
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: documentPageFont,
    color: "#141414",
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
    letterSpacing: 0,
    lineHeight: "18px",
  },
  td: {
    padding: "16px 16px",
    fontSize: 14,
    fontFamily: documentPageFont,
    color: "#141414",
    verticalAlign: "middle" as const,
    borderBottom: "1px solid #e5e5e5",
    lineHeight: "20px",
  },
  link: {
    fontWeight: 600,
    color: "rgb(0, 97, 98)",
    cursor: "pointer",
    textUnderlineOffset: "24%",
    textDecoration: "underline",
    fontFamily: documentPageFont,
    fontSize: 14,
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    padding: 0,
  },
  docName: {
    fontWeight: 600,
    color: "rgb(0, 97, 98)",
    fontFamily: documentPageFont,
    fontSize: 14,
    textDecoration: "underline",
  },
  muted: {
    fontSize: 14,
    fontFamily: documentPageFont,
    color: "#666",
    padding: "24px 16px",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 8,
  },
  actionDivider: {
    color: "#ccc",
    fontWeight: 300,
    fontSize: 14,
    userSelect: "none" as const,
  },
  deleteButton: {
    fontWeight: 600,
    color: "#b71c1c",
    cursor: "pointer",
    fontFamily: documentPageFont,
    fontSize: 14,
    background: "none",
    border: "none",
    padding: 0,
    textDecoration: "underline",
    textUnderlineOffset: "24%",
  },
};

export const termsOfServiceUrl =
  typeof process.env.NEXT_PUBLIC_TERMS_OF_SERVICE_URL === "string"
    ? process.env.NEXT_PUBLIC_TERMS_OF_SERVICE_URL.trim()
    : "";
