// Shared style objects for FAQ sidebars - single source of truth

export const faqSidebarStyles = {
    backdrop: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1000,
      background: 'transparent',
    },
    panel: {
      position: 'fixed' as const,
      top: 0,
      right: 0,
      width: '600px',
      height: '100vh',
      backgroundColor: '#ffffff',
      boxShadow: '-2px 0 8px rgba(0, 0, 0, 0.1)',
      zIndex: 999999,
      display: 'flex' as const,
      flexDirection: 'column' as const,
    },
    header: {
      padding: '20px 24px',
      borderBottom: '1px solid #eaf0f6',
      display: 'flex' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
    },
    headerContent: {
      display: 'flex' as const,
      alignItems: 'center' as const,
      gap: '10px',
    },
    headerTitle: {
      fontSize: '20px',
      fontWeight: 600,
      color: '#141414',
      margin: 0,
    },
    closeButton: {
      background: 'transparent',
      border: 'none',
      padding: '4px',
      cursor: 'pointer',
      color: '#718096',
      display: 'flex' as const,
      alignItems: 'center' as const,
    },
    form: {
      display: 'flex' as const,
      flexDirection: 'column' as const,
      flex: 1,
      minHeight: 0,
    },
    body: {
      flex: 1,
      overflowY: 'auto' as const,
      padding: '40px',
    },
    footer: {
      padding: '16px 24px',
      borderTop: '1px solid #eaf0f6',
      display: 'flex' as const,
      gap: '12px',
    },
    submitButton: (canSubmit: boolean) => ({
      padding: '10px 20px',
      backgroundColor: canSubmit ? '#0091ae' : '#cbd5e0',
      color: '#ffffff',
      border: 'none',
      borderRadius: '4px',
      fontSize: '14px',
      fontWeight: 500 as const,
      cursor: canSubmit ? 'pointer' as const : 'not-allowed' as const,
    }),
    submitButtonHoverActive: '#007a94',
    submitButtonHoverInactive: '#0091ae',
    cancelButton: {
      padding: '10px 20px',
      backgroundColor: 'transparent',
      color: '#141414',
      border: '1px solid #8a8a8a',
      borderRadius: '4px',
      fontSize: '14px',
      fontWeight: 500,
      cursor: 'pointer',
    },
    cancelButtonHover: '#f7fafc',
  };
  
  export const faqFormFieldStyles = {
    container: {
      marginBottom: '20px',
    },
    label: {
      display: 'flex' as const,
      alignItems: 'center' as const,
      gap: '8px',
      fontSize: '14px',
      fontWeight: 600,
      color: '#141414',
      marginBottom: '8px',
    },
    required: {
      color: '#f2545b',
    },
    helpIcon: {
      cursor: 'help' as const,
      color: '#6c757d',
    },
    input: {
      width: '100%',
      padding: '10px 12px',
      border: '1px solid #8a8a8a',
      borderRadius: '4px',
      fontSize: '14px',
      outline: 'none',
    },
    inputFocus: '#0091ae',
    inputBlur: '#8a8a8a',
    textarea: {
      width: '100%',
      padding: '10px 12px',
      border: '1px solid #8a8a8a',
      borderRadius: '4px',
      fontSize: '14px',
      outline: 'none',
      resize: 'vertical' as const,
    },
    hint: {
      fontSize: '0.813rem',
      color: '#6c757d',
      marginTop: '6px',
      display: 'flex' as const,
      alignItems: 'center' as const,
      gap: '4px',
    },
    selectControl: {
      minHeight: 40,
      border: '1px solid #8a8a8a',
      borderRadius: '4px',
      fontSize: '14px',
    },
  };
  export default {};  