import type { WorkloadBoardData, WorkloadGridData } from "@utils/tasks";

// ─── Onboarding status ───────────────────────────────────────────
// Replace these two functions with API calls when backend is ready.
// The key 'workload_onboarding_complete' can map to a user preference field.

const ONBOARDING_KEY = "workload_onboarding_complete";

export function getOnboardingStatus(): boolean {
  try {
    return localStorage.getItem(ONBOARDING_KEY) === "true";
  } catch {
    return false;
  }
}

export function setOnboardingComplete(): void {
  try {
    localStorage.setItem(ONBOARDING_KEY, "true");
  } catch {
    // silently fail — onboarding will show again next visit
  }
}

export function resetOnboardingStatus(): void {
  try {
    localStorage.removeItem(ONBOARDING_KEY);
  } catch {}
}

// ─── Mock data ───────────────────────────────────────────────────
// Replace WORKLOAD_MOCK_BOARD_DATA and WORKLOAD_MOCK_GRID_DATA
// with API responses when backend seed endpoint is ready.
// All consuming components read from these variables — no hardcoded data elsewhere.

const TODAY = new Date();
const fmt = (offset: number) => {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
};

export const WORKLOAD_MOCK_BOARD_DATA: WorkloadBoardData = {
  extension_numbers: ["514", "531", "542", "567", "589"],
  assignee_match: "primary",
  range: { start: fmt(0), end: fmt(6) },
  empty_team: false,
  empty_team_message: null,
  columns: [
    {
      extension_number: "514",
      name: "Usman Ahmed",
      display_name: "Usman Ahmed (514)",
      is_owner: true,
      role: "Team Lead",
      estimated_minutes: 210,
      unestimated_count: 1,
      task_count: 3,
      effective_capacity_minutes_per_day: 480,
      effective_capacity_minutes_period: 2400,
      range_day_count: 5,
      load_percent: 43,
      load_band: "comfortable",
      tasks: [
        {
          id: 1,
          task_id: "mock-1",
          title: "Review Q3 call reports",
          priority: 3,
          due_date: fmt(1),
          is_overdue: false,
          estimated_duration_minutes: 60,
          project_id: 1,
          project_name: "Call Analysis",
          status_id: 1,
          status_name: "In Progress",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "514",
        },
        {
          id: 2,
          task_id: "mock-2",
          title: "Update CRM prospect list",
          priority: 2,
          due_date: fmt(2),
          is_overdue: false,
          estimated_duration_minutes: 90,
          project_id: 2,
          project_name: "CRM",
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "514",
        },
        {
          id: 3,
          task_id: "mock-3",
          title: "Team standup prep",
          priority: 1,
          due_date: fmt(0),
          is_overdue: false,
          estimated_duration_minutes: null,
          project_id: null,
          project_name: null,
          status_id: 3,
          status_name: "Done",
          status_color: null,
          is_completed: true,
          type: "organizational",
          phase: "",
          primary_assignee_extension: "514",
        },
      ],
    },
    {
      extension_number: "531",
      name: "Ahsan Bilal",
      display_name: "Ahsan Bilal (531)",
      is_owner: false,
      role: "Agent",
      estimated_minutes: 480,
      unestimated_count: 1,
      task_count: 3,
      effective_capacity_minutes_per_day: 480,
      effective_capacity_minutes_period: 2400,
      range_day_count: 5,
      load_percent: 95,
      load_band: "near_full",
      tasks: [
        {
          id: 4,
          task_id: "mock-4",
          title: "Configure Cisco Finesse integration",
          priority: 3,
          due_date: fmt(-1),
          is_overdue: true,
          estimated_duration_minutes: 180,
          project_id: 3,
          project_name: "Finesse Setup",
          status_id: 1,
          status_name: "In Progress",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "531",
        },
        {
          id: 5,
          task_id: "mock-5",
          title: "Document agent workflows",
          priority: 2,
          due_date: fmt(3),
          is_overdue: false,
          estimated_duration_minutes: 120,
          project_id: 3,
          project_name: "Finesse Setup",
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "531",
        },
        {
          id: 6,
          task_id: "mock-6",
          title: "Weekly capacity review",
          priority: 1,
          due_date: fmt(4),
          is_overdue: false,
          estimated_duration_minutes: null,
          project_id: null,
          project_name: null,
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "organizational",
          phase: "",
          primary_assignee_extension: "531",
        },
      ],
    },
    {
      extension_number: "542",
      name: "Sara Khan",
      display_name: "Sara Khan (542)",
      is_owner: false,
      role: "Senior Agent",
      estimated_minutes: 540,
      unestimated_count: 0,
      task_count: 2,
      effective_capacity_minutes_per_day: 480,
      effective_capacity_minutes_period: 2400,
      range_day_count: 5,
      load_percent: 112,
      load_band: "overloaded",
      tasks: [
        {
          id: 7,
          task_id: "mock-7",
          title: "Prepare monthly call report",
          priority: 2,
          due_date: fmt(1),
          is_overdue: false,
          estimated_duration_minutes: 240,
          project_id: 1,
          project_name: "Call Analysis",
          status_id: 1,
          status_name: "In Progress",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "542",
        },
        {
          id: 8,
          task_id: "mock-8",
          title: "Train new agents on CRM",
          priority: 3,
          due_date: fmt(0),
          is_overdue: false,
          estimated_duration_minutes: 300,
          project_id: 2,
          project_name: "CRM",
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "organizational",
          phase: "",
          primary_assignee_extension: "542",
        },
      ],
    },
    {
      extension_number: "567",
      name: "Ali Raza",
      display_name: "Ali Raza (567)",
      is_owner: false,
      role: "Agent",
      estimated_minutes: 120,
      unestimated_count: 2,
      task_count: 2,
      effective_capacity_minutes_per_day: 480,
      effective_capacity_minutes_period: 2400,
      range_day_count: 5,
      load_percent: 25,
      load_band: "comfortable",
      tasks: [
        {
          id: 9,
          task_id: "mock-9",
          title: "Review ticket backlog",
          priority: 1,
          due_date: fmt(3),
          is_overdue: false,
          estimated_duration_minutes: null,
          project_id: null,
          project_name: null,
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "567",
        },
        {
          id: 10,
          task_id: "mock-10",
          title: "Update SOP documents",
          priority: 0,
          due_date: fmt(5),
          is_overdue: false,
          estimated_duration_minutes: null,
          project_id: 3,
          project_name: "Finesse Setup",
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "567",
        },
      ],
    },
    {
      extension_number: "589",
      name: "Maria Ahmed",
      display_name: "Maria Ahmed (589)",
      is_owner: false,
      role: "Quality Analyst",
      estimated_minutes: 360,
      unestimated_count: 0,
      task_count: 2,
      effective_capacity_minutes_per_day: 480,
      effective_capacity_minutes_period: 2400,
      range_day_count: 5,
      load_percent: 75,
      load_band: "near_full",
      tasks: [
        {
          id: 11,
          task_id: "mock-11",
          title: "QA call recordings batch 3",
          priority: 2,
          due_date: fmt(2),
          is_overdue: false,
          estimated_duration_minutes: 180,
          project_id: 1,
          project_name: "Call Analysis",
          status_id: 1,
          status_name: "In Progress",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "589",
        },
        {
          id: 12,
          task_id: "mock-12",
          title: "Submit quality scorecard",
          priority: 3,
          due_date: fmt(1),
          is_overdue: false,
          estimated_duration_minutes: 180,
          project_id: null,
          project_name: null,
          status_id: 2,
          status_name: "New",
          status_color: null,
          is_completed: false,
          type: "task",
          phase: "",
          primary_assignee_extension: "589",
        },
      ],
    },
  ],
};

export const WORKLOAD_MOCK_GRID_DATA: WorkloadGridData = {
  extension_numbers: ["514", "531", "542", "567", "589"],
  assignee_match: "primary",
  timezone: "Asia/Dubai",
  range: { start: fmt(0), end: fmt(6) },
  empty_team: false,
  empty_team_message: null,
  members: [
    { extension_number: "514", name: "Usman Ahmed", display_name: "Usman Ahmed (514)", is_owner: true, role: "Team Lead" },
    { extension_number: "531", name: "Ahsan Bilal", display_name: "Ahsan Bilal (531)", is_owner: false, role: "Agent" },
    { extension_number: "542", name: "Sara Khan", display_name: "Sara Khan (542)", is_owner: false, role: "Senior Agent" },
    { extension_number: "567", name: "Ali Raza", display_name: "Ali Raza (567)", is_owner: false, role: "Agent" },
    { extension_number: "589", name: "Maria Ahmed", display_name: "Maria Ahmed (589)", is_owner: false, role: "Quality Analyst" },
  ],
  days: [fmt(0), fmt(1), fmt(2), fmt(3), fmt(4)],
  cells: [
    { extension_number: "514", date: fmt(0), estimated_minutes: 60, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 12, load_band: "comfortable", has_unestimated: false },
    { extension_number: "514", date: fmt(1), estimated_minutes: 60, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 12, load_band: "comfortable", has_unestimated: false },
    { extension_number: "514", date: fmt(2), estimated_minutes: 90, unestimated_count: 1, task_count: 1, effective_capacity_minutes: 480, load_percent: 18, load_band: "comfortable", has_unestimated: true },
    { extension_number: "514", date: fmt(3), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "514", date: fmt(4), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "531", date: fmt(0), estimated_minutes: 180, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 37, load_band: "comfortable", has_unestimated: false },
    { extension_number: "531", date: fmt(1), estimated_minutes: 420, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 87, load_band: "near_full", has_unestimated: false },
    { extension_number: "531", date: fmt(2), estimated_minutes: 480, unestimated_count: 1, task_count: 1, effective_capacity_minutes: 480, load_percent: 100, load_band: "overloaded", has_unestimated: true },
    { extension_number: "531", date: fmt(3), estimated_minutes: 120, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 25, load_band: "comfortable", has_unestimated: false },
    { extension_number: "531", date: fmt(4), estimated_minutes: 0, unestimated_count: 1, task_count: 1, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: true },
    { extension_number: "542", date: fmt(0), estimated_minutes: 300, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 62, load_band: "comfortable", has_unestimated: false },
    { extension_number: "542", date: fmt(1), estimated_minutes: 540, unestimated_count: 0, task_count: 2, effective_capacity_minutes: 480, load_percent: 112, load_band: "overloaded", has_unestimated: false },
    { extension_number: "542", date: fmt(2), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "542", date: fmt(3), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "542", date: fmt(4), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "567", date: fmt(0), estimated_minutes: 0, unestimated_count: 1, task_count: 1, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: true },
    { extension_number: "567", date: fmt(1), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "567", date: fmt(2), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "567", date: fmt(3), estimated_minutes: 0, unestimated_count: 1, task_count: 1, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: true },
    { extension_number: "567", date: fmt(4), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "589", date: fmt(0), estimated_minutes: 180, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 37, load_band: "comfortable", has_unestimated: false },
    { extension_number: "589", date: fmt(1), estimated_minutes: 360, unestimated_count: 0, task_count: 2, effective_capacity_minutes: 480, load_percent: 75, load_band: "near_full", has_unestimated: false },
    { extension_number: "589", date: fmt(2), estimated_minutes: 180, unestimated_count: 0, task_count: 1, effective_capacity_minutes: 480, load_percent: 37, load_band: "comfortable", has_unestimated: false },
    { extension_number: "589", date: fmt(3), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
    { extension_number: "589", date: fmt(4), estimated_minutes: 0, unestimated_count: 0, task_count: 0, effective_capacity_minutes: 480, load_percent: 0, load_band: "available", has_unestimated: false },
  ],
};
