const currenciesData = [
  { code: "USD", country: "United States", name: "US Dollar", symbol: "$" },
  { code: "EUR", country: "European Union", name: "Euro", symbol: "€" },
  { code: "GBP", country: "United Kingdom", name: "British Pound", symbol: "£" },
  { code: "JPY", country: "Japan", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", country: "Australia", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", country: "Canada", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", country: "Switzerland", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", country: "China", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", country: "India", name: "Indian Rupee", symbol: "₹" },
  { code: "SGD", country: "Singapore", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", country: "Hong Kong", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NZD", country: "New Zealand", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "SEK", country: "Sweden", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", country: "Norway", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", country: "Denmark", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", country: "Poland", name: "Polish Zloty", symbol: "zł" },
  { code: "MXN", country: "Mexico", name: "Mexican Peso", symbol: "$" },
  { code: "BRL", country: "Brazil", name: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", country: "South Africa", name: "South African Rand", symbol: "R" },
  { code: "KRW", country: "South Korea", name: "South Korean Won", symbol: "₩" },
  { code: "TRY", country: "Turkey", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", country: "Russia", name: "Russian Ruble", symbol: "₽" },
  { code: "AED", country: "United Arab Emirates", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", country: "Saudi Arabia", name: "Saudi Riyal", symbol: "﷼" },
  { code: "ILS", country: "Israel", name: "Israeli Shekel", symbol: "₪" },
  { code: "THB", country: "Thailand", name: "Thai Baht", symbol: "฿" },
  { code: "MYR", country: "Malaysia", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "PHP", country: "Philippines", name: "Philippine Peso", symbol: "₱" },
  { code: "IDR", country: "Indonesia", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "VND", country: "Vietnam", name: "Vietnamese Dong", symbol: "₫" },
  { code: "EGP", country: "Egypt", name: "Egyptian Pound", symbol: "£" },
  { code: "PKR", country: "Pakistan", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BGN", country: "Bulgaria", name: "Bulgarian Lev", symbol: "лв" },
  { code: "CZK", country: "Czech Republic", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", country: "Hungary", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", country: "Romania", name: "Romanian Leu", symbol: "lei" },
  { code: "ISK", country: "Iceland", name: "Icelandic Krona", symbol: "kr" },
  { code: "HRK", country: "Croatia", name: "Croatian Kuna", symbol: "kn" },
  { code: "ARS", country: "Argentina", name: "Argentine Peso", symbol: "$" },
  { code: "CLP", country: "Chile", name: "Chilean Peso", symbol: "$" },
  { code: "COP", country: "Colombia", name: "Colombian Peso", symbol: "$" },
  { code: "PEN", country: "Peru", name: "Peruvian Sol", symbol: "S/" },
  { code: "NGN", country: "Nigeria", name: "Nigerian Naira", symbol: "₦" },
  { code: "KES", country: "Kenya", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "TZS", country: "Tanzania", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UGX", country: "Uganda", name: "Ugandan Shilling", symbol: "USh" },
  { code: "GHS", country: "Ghana", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "XOF", country: "West Africa", name: "CFA Franc", symbol: "CFA" },
  { code: "XAF", country: "Central Africa", name: "CFA Franc", symbol: "CFA" },
  { code: "MAD", country: "Morocco", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "TND", country: "Tunisia", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "JOD", country: "Jordan", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "LBP", country: "Lebanon", name: "Lebanese Pound", symbol: "£" },
  { code: "IQD", country: "Iraq", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "KWD", country: "Kuwait", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "OMR", country: "Oman", name: "Omani Rial", symbol: "﷼" },
  { code: "QAR", country: "Qatar", name: "Qatari Riyal", symbol: "﷼" },
  { code: "BHD", country: "Bahrain", name: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "LKR", country: "Sri Lanka", name: "Sri Lankan Rupee", symbol: "₨" },
  { code: "BDT", country: "Bangladesh", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "NPR", country: "Nepal", name: "Nepalese Rupee", symbol: "₨" },
  { code: "MMK", country: "Myanmar", name: "Myanmar Kyat", symbol: "K" },
  { code: "KHR", country: "Cambodia", name: "Cambodian Riel", symbol: "៛" },
  { code: "LAK", country: "Laos", name: "Lao Kip", symbol: "₭" },
  { code: "BND", country: "Brunei", name: "Brunei Dollar", symbol: "B$" },
  { code: "FJD", country: "Fiji", name: "Fijian Dollar", symbol: "FJ$" },
  { code: "PGK", country: "Papua New Guinea", name: "Papua New Guinean Kina", symbol: "K" },
  { code: "SBD", country: "Solomon Islands", name: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "VUV", country: "Vanuatu", name: "Vanuatu Vatu", symbol: "Vt" },
  { code: "WST", country: "Samoa", name: "Samoan Tala", symbol: "WS$" },
  { code: "XPF", country: "French Polynesia", name: "CFP Franc", symbol: "₣" },
  { code: "TOP", country: "Tonga", name: "Tongan Paʻanga", symbol: "T$" },
  { code: "UAH", country: "Ukraine", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "BYN", country: "Belarus", name: "Belarusian Ruble", symbol: "Br" },
  { code: "MDL", country: "Moldova", name: "Moldovan Leu", symbol: "lei" },
  { code: "GEL", country: "Georgia", name: "Georgian Lari", symbol: "₾" },
  { code: "AMD", country: "Armenia", name: "Armenian Dram", symbol: "֏" },
  { code: "AZN", country: "Azerbaijan", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "KZT", country: "Kazakhstan", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "KGS", country: "Kyrgyzstan", name: "Kyrgystani Som", symbol: "с" },
  { code: "TJS", country: "Tajikistan", name: "Tajikistani Somoni", symbol: "ЅМ" },
  { code: "TMT", country: "Turkmenistan", name: "Turkmenistani Manat", symbol: "T" },
  { code: "UZS", country: "Uzbekistan", name: "Uzbekistani Som", symbol: "so'm" },
  { code: "MNT", country: "Mongolia", name: "Mongolian Tugrik", symbol: "₮" },
  { code: "AFN", country: "Afghanistan", name: "Afghan Afghani", symbol: "؋" },
  { code: "IRR", country: "Iran", name: "Iranian Rial", symbol: "﷼" },
  { code: "YER", country: "Yemen", name: "Yemeni Rial", symbol: "﷼" },
  { code: "SYP", country: "Syria", name: "Syrian Pound", symbol: "£" },
  { code: "JMD", country: "Jamaica", name: "Jamaican Dollar", symbol: "J$" },
  { code: "BBD", country: "Barbados", name: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BZD", country: "Belize", name: "Belize Dollar", symbol: "BZ$" },
  { code: "BMD", country: "Bermuda", name: "Bermudian Dollar", symbol: "BD$" },
  { code: "BSD", country: "Bahamas", name: "Bahamian Dollar", symbol: "B$" },
  { code: "TTD", country: "Trinidad and Tobago", name: "Trinidadian Dollar", symbol: "TT$" },
  { code: "GYD", country: "Guyana", name: "Guyanese Dollar", symbol: "G$" },
  { code: "SRD", country: "Suriname", name: "Surinamese Dollar", symbol: "Sr$" },
  { code: "BOB", country: "Bolivia", name: "Bolivian Boliviano", symbol: "Bs." },
  { code: "PYG", country: "Paraguay", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "UYU", country: "Uruguay", name: "Uruguayan Peso", symbol: "$U" },
  { code: "CRC", country: "Costa Rica", name: "Costa Rican Colon", symbol: "₡" },
  { code: "PAB", country: "Panama", name: "Panamanian Balboa", symbol: "B/." },
  { code: "GTQ", country: "Guatemala", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HNL", country: "Honduras", name: "Honduran Lempira", symbol: "L" },
  { code: "NIO", country: "Nicaragua", name: "Nicaraguan Cordoba", symbol: "C$" },
  { code: "DOP", country: "Dominican Republic", name: "Dominican Peso", symbol: "RD$" },
  { code: "HTG", country: "Haiti", name: "Haitian Gourde", symbol: "G" },
  { code: "CUP", country: "Cuba", name: "Cuban Peso", symbol: "₱" },
  { code: "XCD", country: "Eastern Caribbean", name: "East Caribbean Dollar", symbol: "₱" },
  { code: "AWG", country: "Aruba", name: "Aruban Florin", symbol: "ƒ" },
  { code: "ANG", country: "Netherlands Antilles", name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { code: "BWP", country: "Botswana", name: "Botswana Pula", symbol: "P" },
  { code: "ZWL", country: "Zimbabwe", name: "Zimbabwean Dollar", symbol: "$" },
  { code: "ZMW", country: "Zambia", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "MWK", country: "Malawi", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MZN", country: "Mozambique", name: "Mozambican Metical", symbol: "MT" },
  { code: "AOA", country: "Angola", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "ETB", country: "Ethiopia", name: "Ethiopian Birr", symbol: "Br" },
  { code: "DJF", country: "Djibouti", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "SOS", country: "Somalia", name: "Somali Shilling", symbol: "S" },
  { code: "ERN", country: "Eritrea", name: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "SDG", country: "Sudan", name: "Sudanese Pound", symbol: "ج.س." },
  { code: "SSP", country: "South Sudan", name: "South Sudanese Pound", symbol: "£" },
  { code: "LRD", country: "Liberia", name: "Liberian Dollar", symbol: "$" },
  { code: "SLL", country: "Sierra Leone", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "GMD", country: "Gambia", name: "Gambian Dalasi", symbol: "D" },
  { code: "GNF", country: "Guinea", name: "Guinean Franc", symbol: "FG" },
  { code: "MGA", country: "Madagascar", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "MUR", country: "Mauritius", name: "Mauritian Rupee", symbol: "₨" },
  { code: "SCR", country: "Seychelles", name: "Seychellois Rupee", symbol: "₨" },
  { code: "KMF", country: "Comoros", name: "Comorian Franc", symbol: "CF" },
  { code: "RWF", country: "Rwanda", name: "Rwandan Franc", symbol: "RF" },
  { code: "BIF", country: "Burundi", name: "Burundian Franc", symbol: "FBu" },
  { code: "ALL", country: "Albania", name: "Albanian Lek", symbol: "Lek" },
  { code: "MKD", country: "North Macedonia", name: "Macedonian Denar", symbol: "ден" },
  { code: "RSD", country: "Serbia", name: "Serbian Dinar", symbol: "дин." },
  { code: "BAM", country: "Bosnia and Herzegovina", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
];

export { currenciesData };

