import type { CSSProperties } from "react";

export const companyInfoFont = "Lexend Deca, Helvetica, Arial, sans-serif";

export const companyInfoStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily: companyInfoFont,
    color: "#141414",
    backgroundColor: "#f5f5f5",
    minHeight: "100vh",
    padding: "24px",
    maxWidth: "calc(1376px)",
    margin: "0 auto",
    boxSizing: "border-box" as const,
  },
  pageHeading: {
    fontSize: 24,
    fontWeight: 300,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 16px 0",
    lineHeight: "29px",
  },
  card: {
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    width: "100%",
    backgroundColor: "rgb(255, 255, 255)",
    boxShadow: "rgba(20, 20, 20, 0.08) 0px 1px 8px 0px",
    border: "1px solid rgb(204, 204, 204)",
    marginBottom: 16,
    borderRadius: 8,
    boxSizing: "border-box" as const,
    overflow: "hidden",
  },
  cardPadding: {
    padding: "24px",
  },
  btnLight: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 4,
    color: "#141414",
    fontFamily: companyInfoFont,
    fontSize: 12,
    fontWeight: 400,
    lineHeight: "14px",
    padding: "8px 16px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    transition: "150ms ease-out",
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: 700,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 4px 0",
    lineHeight: "18px",
  },
  fieldValue: {
    fontSize: 14,
    fontWeight: 400,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: 0,
    lineHeight: "22px",
  },
  infoRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "20px 24px",
    borderBottom: "1px solid #f0f0f0",
  },
  infoLeft: {
    display: "flex",
    gap: 20,
    flex: 1,
    alignItems: "flex-start",
  },
  sectionHeadingRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionHeading: {
    fontSize: 24,
    fontWeight: 300,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: 0,
    lineHeight: "29px",
  },
  link: {
    fontWeight: 600,
    color: "rgb(0, 97, 98)",
    cursor: "pointer",
    textUnderlineOffset: "24%",
    textDecoration: "underline",
    fontFamily: companyInfoFont,
    fontSize: 14,
  },
  contactCard: {
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 8,
    padding: "24px",
    backgroundColor: "#fff",
    flex: 1,
  },
  contactHeading: {
    fontSize: 20,
    fontWeight: 600,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 12px 0",
    lineHeight: "24px",
  },
  contactDesc: {
    fontSize: 14,
    fontWeight: 400,
    fontFamily: companyInfoFont,
    color: "#444",
    margin: "0 0 20px 0",
    lineHeight: "21px",
  },
  selectLabel: {
    fontSize: 14,
    fontWeight: 600,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 3px 0",
    display: "block",
  },
  selectRequired: {
    fontSize: 12,
    fontWeight: 400,
    fontFamily: companyInfoFont,
    color: "rgb(0, 97, 98)",
    margin: "0 0 8px 0",
    display: "block",
  },
  selectBox: {
    width: "100%",
    height: 40,
    border: "1px solid rgb(138, 138, 138)",
    borderRadius: 4,
    backgroundColor: "#fff",
    fontFamily: companyInfoFont,
    fontSize: 14,
    color: "#141414",
    paddingInline: 12,
    appearance: "none" as const,
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='%23666' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
    cursor: "pointer",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  addAnother: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    color: "rgb(0, 97, 98)",
    fontWeight: 600,
    fontSize: 14,
    fontFamily: companyInfoFont,
    cursor: "pointer",
    textDecoration: "none",
    marginTop: 12,
    border: "none",
    background: "none",
    padding: 0,
  },
  otherContactsCard: {
    border: "1px solid rgb(204, 204, 204)",
    borderRadius: 8,
    padding: "24px",
    backgroundColor: "#fff",
  },
  otherContactsHeading: {
    fontSize: 20,
    fontWeight: 600,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 20px 0",
    lineHeight: "24px",
  },
  otherRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    paddingBottom: 20,
    marginBottom: 20,
    borderBottom: "1px solid #f0f0f0",
    alignItems: "start",
  },
  otherRowLast: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    alignItems: "start",
  },
  otherContactName: {
    fontSize: 14,
    fontWeight: 700,
    fontFamily: companyInfoFont,
    color: "#141414",
    margin: "0 0 4px 0",
  },
  otherContactDesc: {
    fontSize: 13,
    fontWeight: 400,
    fontFamily: companyInfoFont,
    color: "#444",
    margin: 0,
    lineHeight: "19px",
  },
};
